### ISSUE TITLE
Implementation of session management and authentication

### ISSUE THREAD

**Issue by papuruth** [papuruth/JobPortal#5]
Currently the session management is done using local storage but any enhancement to it would be welcomed

**Comment by PranjalAgni** [comment]
I would like to work on this

**Comment by papuruth** [comment]
Sure

**Comment by PranjalAgni** [comment]
I am thinking of implementing token-based authentication system for which I will have to change the back-end. Is it fine?

Also another approach I have is storing the `currentUser` object in a cookie with the help of [react-cookie](https://www.npmjs.com/package/react-cookie). This will undergo a lot of change as everywhere you have used `localstorage.getItem('currentUser')` to get the user information, it would have been great if you store this information in `redux-store`.

**Comment by papuruth** [comment]
> I am thinking of implementing token-based authentication system for which I will have to change the back-end. Is it fine?
> 
> Also another approach I have is storing the `currentUser` object in a cookie with the help of [react-cookie](https://www.npmjs.com/package/react-cookie). This will undergo a lot of change as everywhere you have used `localstorage.getItem('currentUser')` to get the user information, it would have been great if you store this information in `redux-store`.

Sure you can go ahead. But please write clean code and appropriate commenting

**Comment by PranjalAgni** [comment]
> Sure you can go ahead. But please write clean code and appropriate commenting

It would be good if you set up linter for back-end, that way everyone can be on the same page.

**Comment by papuruth** [comment]
Okay I'll do that

**Comment by papuruth** [comment]
@PranjalAgni Please install the eslint extension in vscode

**Comment by papuruth** [comment]
@PranjalAgni  The backend eslint is conflicting with the react eslint

**Comment by PranjalAgni** [comment]
As you have generated the client using `create-react-app` it has its default eslint configuration which comes bundled with React. You can add a `.eslintrc` file in the root of the project which will be used for server then

**Comment by papuruth** [comment]
Did you cloned my code?

**Comment by PranjalAgni** [comment]
Yup.

**Comment by papuruth** [comment]
Started working?

**Comment by papuruth** [comment]
> As you have generated the client using `create-react-app` it has its default eslint configuration which comes bundled with React. You can add a `.eslintrc` file in the root of the project which will be used for server then.

the problem is that the backend is in root of project and frontend code is in client directory

**Comment by PranjalAgni** [comment]
> the problem is that the backend is in root of project and frontend code is in client directory

You can place a `.eslintrc` file in the root and it will be good to go.

**Comment by papuruth** [comment]
Btw i did by placing  `.eslintrc.js` in both and now its fine

**Comment by PranjalAgni** [comment]
Sure.

**Comment by papuruth** [comment]
@PranjalAgni are you working on this or should I close the issue?
